[package]
# Use Python 3.11 as the base image
runtime = "python:3.11"

# System packages needed
systems = [
    "wget",
    "gnupg",
    "unzip",
    "curl",
    "chromium"  # Using Chromium instead of Google Chrome for better Nix compatibility
]

[build]
buildCmd = '''
    # Install system dependencies
    apt-get update && \
    apt-get install -y wget gnupg unzip curl

    # Find and install ChromeDriver
    CHROME_VERSION=$(chromium-browser --version | cut -d ' ' -f 2 | cut -d '.' -f 1) && \
    CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) && \
    ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then DRIVER_ARCH="linux64"; \
    elif [ "$ARCH" = "aarch64" ]; then DRIVER_ARCH="linux64_arm64"; \
    else DRIVER_ARCH="linux64"; fi && \
    wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_${DRIVER_ARCH}.zip -P /tmp && \
    unzip /tmp/chromedriver_${DRIVER_ARCH}.zip -d /tmp && \
    mv /tmp/chromedriver /usr/local/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver

    # Install Python dependencies
    pip install -r requirements.txt
'''

# Start command for the application
[start]
cmd = "uvicorn seek_scraper_BS_v7:app --host 0.0.0.0 --port $PORT"

# Expose the port
[ports]
web = "$PORT"
